- name: docker build and push
  hosts: 192.168.146.128 # Replace with the hostname or IP address of your target server
  become: true  # Run tasks with sudo privileges

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes   

    - name: Build Docker Image
      command: docker build -t petstore .
      args:
        chdir: /var/lib/jenkins/workspace/petstore

    - name: tag image
      command: docker tag petstore:latest nileshdoc141/petstore:latest 

    - name: Log in to Docker Hub
      community.docker.docker_login:
        registry_url: https://index.docker.io/v1/
        username: nileshdoc141
        password: Docker@123

    - name: Push image
      command: docker push nileshdoc141/petstore:latest

    - name: Run container
      command: docker run -d --name pet1 -p 8081:8080 nileshdoc141/petstore:latest
